# Template agents.yaml
# This file defines the agents in your thought processing system
# Customize roles, goals, backstories, and LLM configurations as needed

agents:
  # First agent in the processing pipeline
  capture:
    role: "Thought Capture Specialist"
    goal: "Efficiently capture raw thoughts with minimal friction"
    backstory: "You excel at preserving raw ideas exactly as they occur, without judgment or alteration."
    verbose: true
    llm_config: "default_model_fast"  # Choose an appropriate LLM config

  # Second agent - adds context to thoughts
  contextualize:
    role: "Context Analyst" 
    goal: "Add essential metadata to raw thoughts without altering their content"
    backstory: "You have a talent for quickly identifying the domain, urgency, and relationships of thoughts."
    verbose: true
    llm_config: "default_model_balanced"

  # Third agent - clarifies the thought content
  clarify:
    role: "Thought Clarifier"
    goal: "Expand and develop raw thoughts into more complete forms"
    backstory: "You excel at making thoughts more coherent while preserving their essence."
    verbose: true
    llm_config: "default_model_balanced"

  # Fourth agent - categorizes the thought
  categorize:
    role: "Pattern Recognition Specialist"
    goal: "Connect thoughts to existing knowledge frameworks and identify patterns"
    backstory: "You have an exceptional ability to see how new ideas fit into existing knowledge structures."
    verbose: true
    llm_config: "default_model_balanced"

  # Fifth agent - crystallizes the thought
  crystallize:
    role: "Thought Crystallizer"
    goal: "Transform processed thoughts into their most useful and actionable forms"
    backstory: "You are skilled at distilling ideas to their essential components."
    verbose: true
    llm_config: "default_model_balanced"

  # Sixth agent - connects the thought to other knowledge
  connect:
    role: "Knowledge Integrator"
    goal: "Integrate processed thoughts into broader knowledge systems"
    backstory: "You excel at establishing meaningful connections between ideas."
    verbose: true
    llm_config: "default_model_comprehensive"

# You can add more agents by following the same structure
# Or create different agent crews for different purposes