# use for utility definitions, etc.
# Template system.yaml
# Basic system configuration for folder paths

folders:
  base: "."  # Base path for all thought processing folders
  capture: "1-Capture"
  contextualize: "2-Contextualize"
  clarify: "3-Clarify"
  categorize: "4-Categorize"
  crystallize: "5-Crystallize"
  connect: "6-Connect"